#!/bin/bash

if [ -f /etc/profile.d/puppet-agent.sh ] ; then
    . /etc/profile.d/puppet-agent.sh
else
    export PATH=$PATH:/opt/puppetlabs/bin
fi

set -e

cd $( dirname "$0" ) || :

git submodule update --init

puppet resource file "$HOME/.vimrc" ensure=link target="$( pwd )/.vimrc"
puppet resource file "$HOME/.vim" ensure=link target="$( pwd )"

if [ "$( facter os.family )" = RedHat ] ; then
    sudo $( which puppet ) resource package rubygem-puppet-lint ensure=installed
else
    sudo $( which puppet ) resource package puppet-lint provider=gem ensure=installed
fi
