#!/bin/bash

set -e

git submodule update --init

puppet resource file "$HOME/.vimrc" ensure=link target="$( pwd )/.vimrc"
puppet resource file "$HOME/.vim" ensure=link target="$( pwd )"

puppet resource package puppet-lint provider=gem ensure=installed
